// Centralized UI strings — all user-visible text lives here.
// Static text is a plain string value; dynamic text is a factory function.

export const STRINGS = {

  APP: {
    BOOT_INITIALISING:   'Initialising backend',
    BOOT_FAILED:         'Backend failed to start',
    NO_LOCATION:         'Set your location in Settings → Location for astronomy features to work correctly.',
    BREADCRUMB_HOME:     '01 Home',
    BREADCRUMB_SETTINGS: '03 Settings',
    breadcrumbFeature:   (name: string) => `02 ${name}`,
  },

  TOPBAR: {
    HOME:          'Home',
    SETTINGS:      'Settings',
    SETTINGS_ARIA: 'Settings',
    VERSION:       'V1.0 · BUILD 1.0.1 ALPHA',
  },

  SIDEBAR: {
    EXPORT:       'Export',
    EXPORT_ARIA:  'Export',
    DOCS:         'Docs',
    DOCS_ARIA:    'Documentation',
  },

  THEME_TOGGLE: {
    GROUP_ARIA: 'Theme',
    DARK:       'Dark',
    LIGHT:      'Light',
  },

  NOTIFICATION_TRAY: {
    BELL_ARIA:    'Notifications',
    TRAY_ARIA:    'Notification tray',
    TITLE:        'Notifications',
    CLOSE_ARIA:   'Close',
    STAT_TOTAL:   'total',
    STAT_ERRORS:  'errors',
    TAB_ALL:      'All',
    TAB_ALERTS:   'Alerts',
    TAB_ACTIVITY: 'Activity',
    GROUP_TODAY:   'Today',
    GROUP_EARLIER: 'Earlier',
    EMPTY_TITLE:   'All caught up',
    DISMISS:       'Dismiss',
    CLEAR_ALL:     'Clear all',
    KIND_ERROR:    'Error',
    KIND_WARN:     'Warning',
    KIND_INFO:     'Info',
    KIND_SUCCESS:  'Success',
    KIND_PROGRESS: 'Running',
    TIME_NOW:       'now',
    TIME_YESTERDAY: 'Yesterday',
    timeMinAgo:     (n: number) => `${n} min ago`,
    timeHrAgo:      (n: number) => `${n} hr ago`,
    liveRunning:    (n: number) => `Live · ${n} task${n !== 1 ? 's' : ''} running`,
    emptyNotices:   (filter: string) => `No ${filter !== 'all' ? filter + ' ' : ''}notifications.`,
  },

  TOAST: {
    DISMISS_ARIA: 'Dismiss',
  },

  HOME: {
    EYEBROW:      'Astrophotography Toolkit',
    BYLINE:       'by @astroradu',
    POWERED_LABEL:'POWERED BY',
    POWERED_TECH: 'Python · HyperLeda · Simbad',
    CARD_FOOTER:  'OPEN MODULE',
    COORD_LAT:    'LAT',
    COORD_LNG:    'LNG',
  },

  SETTINGS: {
    BACK:    'Back',
    TITLE:   'Settings',
    SUBTITLE:'Get RedShift set up with what you need and tweak it to your liking.',
    SECTION_LOCATION_EYEBROW:  'Section · 01',
    SECTION_LOCATION_TITLE:    'Location',
    SECTION_LOCATION_DESC:     'A rough location area that all your astronomy tools can use for calculations.',
    SECTION_APPEARANCE_EYEBROW:'Section · 02',
    SECTION_APPEARANCE_TITLE:  'Appearance',
    SECTION_APPEARANCE_DESC:   'Switch between light and dark surfaces.',
    SECTION_PALETTE_EYEBROW:   'Section · 03',
    SECTION_PALETTE_TITLE:     'Color palette',
    SECTION_PALETTE_DESC:      'Pick a color palette that feels like you.',
    MODE_DARK_LABEL:  'Dark',
    MODE_DARK_SUB:    'Default · low light',
    MODE_LIGHT_LABEL: 'Light',
    MODE_LIGHT_SUB:   'Daytime · high contrast',
    modeLabel:        (m: string) => m === 'dark' ? 'Dark' : 'Light',
    errSave:          (msg: string) => `Could not save settings: ${msg}`,
  },

  LOCATION: {
    BTN_SYSTEM:      'Get System Location',
    BTN_LOCATING:    'Locating…',
    SOURCE_SYSTEM:   'Source · System',
    SOURCE_MANUAL:   'Source · Manual',
    SOURCE_NONE:     'No location set',
    LABEL_LAT:       'Latitude',
    LABEL_LNG:       'Longitude',
    PLACEHOLDER_LAT: '',
    PLACEHOLDER_LNG: '',
    BTN_SAVE:        'Save',
    BTN_SAVED:       'Saved',
    ERR_INVALID:     'Invalid coordinates. Latitude must be -90 to 90, longitude -180 to 180.',
    ERR_LAT:         'Latitude must be a number between -90 and 90.',
    ERR_LNG:         'Longitude must be a number between -180 and 180.',
  },

  PAGINATION: {
    ARIA:      'Pagination',
    PREV_ARIA: 'Previous page',
    NEXT_ARIA: 'Next page',
    singlePage:(total: number) => `${total.toLocaleString()} rows · single page`,
    range:     (start: number, end: number, total: number) =>
                 `${start.toLocaleString()}–${end.toLocaleString()} of ${total.toLocaleString()}`,
  },

  PLANNER_TABLE: {
    TOTAL:        'Total',
    BEST_DEFAULT: 'Best',
  },

  PLANNER: {
    PERIODS: ['1 Month', '3 Months', '6 Months', 'One Year'] as const,
    NO_LOCATION:   'No location set. Please configure your location in Settings before running the planner.',
    META_LAT:      'LAT',
    META_LON:      'LON',
    META_SAMPLE:   'SAMPLE',
    META_SOURCE:   'SOURCE',
    SOURCE_GPS:    'GPS',
    SOURCE_MANUAL: 'MANUAL',
    SOURCE_DASH:   '—',
    BTN_CALCULATE: 'Calculate',
    FOOTER_LAT:    'LAT',
    FOOTER_LNG:    'LNG',
    FOOTER_NO_LOCATION: '—',
    FOOTER_ENGINE: 'Engine',
    FOOTER_ENGINE_VAL: 'astropy 6.1',
    BTN_BACK:      'Back',
    ACTIVE_SESSION:            'Active Session',
    ACTIVE_SESSION_JUMP_ARIA:  'Open active session results',
    ACTIVE_SESSION_CLEAR_ARIA: 'Clear active session',
    OVERWRITE_NOTE:            'Calculating will overwrite the current Active Session.',
  },

  CONSTELLATION_PLANNER: {
    TITLE:    'Constellation Planner',
    SUBTITLE: 'Plan your shoots by checking which constellations stick around longest and sit highest in the sky.',
    DESC:     'Plan imaging shooting by constellation. Select the time frame ahead:',
    EYEBROW:  'RUNNING · constellation_scorer.py',
    FOOTER_SAMPLE:     'Sample',
    FOOTER_SAMPLE_VAL: '88 constellations',
    STATUSES: [
      'Loading constellation data',
      'Building observer',
      'Precomputing twilight windows',
      'Computing altitudes',
      'Scoring constellations',
    ] as const,
  },

  GALAXY_PLANNER: {
    TITLE:    'Galaxy Planner',
    SUBTITLE: 'Scout your best shooting spots by finding galaxies that hang around all night and stay near zenith.',
    DESC:     'Score thousands of galaxies by visibility. Select the time frame ahead:',
    EYEBROW:  'RUNNING · galaxy_scorer.py',
    FOOTER_CATALOGUE:     'Catalogue',
    FOOTER_CATALOGUE_VAL: 'PGC large galaxies',
    ANG_SIZE_LABEL: 'Angular Size',
    ANG_SIZE_ARIA:  'Minimum angular size filter',
    NONSTANDARD_TITLE: 'Compute non-standard galactic types',
    NONSTANDARD_DESC:  'Include unconfirmed and non-galaxy PGC entries. Off by default — only canonical galaxies (objtype = G) are scored.',
    STATUSES: [
      'Loading galaxy catalogue',
      'Building observer',
      'Precomputing twilight windows',
      'Computing altitudes',
      'Scoring galaxies',
    ] as const,
  },

  PLANNER_RESULTS: {
    TITLE:               'Visibility Forecast',
    subtitle:            (period: string, count: number) =>
                           `${period} window · ${count} constellations`,
    KPI_TOP:             'TOP CONSTELLATION',
    KPI_PEAK:            'PEAK MONTH',
    KPI_RUNTIME:         'ENGINE RUNTIME',
    CARD_TOP_EYEBROW:    'TOP CONSTELLATION · HIGHEST SCORE',
    cardTopDesc:         (period: string) =>
                           `Best imaging window across the ${period.toLowerCase()} forecast.`,
    CARD_NOCIRC_EYEBROW: 'TOP NON-CIRCUMPOLAR · BEST RISING TARGET',
    CARD_NOCIRC_DESC:    'Best constellation that actually rises and sets — a defined imaging window, far from the celestial pole.',
    SCORE_LABEL:         'visibility score',
    META_BEST_MONTH:     'Best month',
    META_PEAK_SCORE:     'Peak score',
    META_SKY_BEHAVIOUR:  'Sky behaviour',
    SKY_CIRCUMPOLAR:     'Circumpolar',
    SKY_RISES:           'Rises & sets',
    TABLE_NAME_HEADER:   'Constellation',
    TABLE_TITLE:         'Visibility score per month',
    CHIP_HEATMAP:        'Heatmap',
    CHIP_NUMBERS:        'Numbers',
    CHIP_SPARKLINE:      'Sparkline',
  },

  GALAXY_RESULTS: {
    TITLE:    'Galaxy Visibility Forecast',
    subtitle: (period: string, total: number, nonstandard: boolean) =>
                `${period} window · ${total.toLocaleString()} galaxies${nonstandard ? ' (all objtypes)' : ' (objtype = G)'}`,
    KPI_ROWS:    'SCORED ROWS',
    KPI_PEAK:    'TOP PEAK MONTH',
    KPI_RUNTIME: 'ENGINE RUNTIME',
    TABLE_NAME_HEADER: 'PGC',
    TABLE_BEST_HEADER: 'Best Month',
    TABLE_TITLE:       'Visibility score per month · click any row for details',
    countPill:         (page: number, totalPages: number, pageSize: number) =>
                         `page ${page} of ${totalPages} · ${pageSize}/page`,
  },

  GALAXY_DETAIL: {
    FIELD_PRIMARY_NAME:  'Primary name',
    FIELD_OBJECT_TYPE:   'Object type',
    FIELD_PGC_ID:        'PGC ID',
    FIELD_ALIASES:       'Aliases',
    FIELD_RA:            'Right ascension',
    FIELD_DEC:           'Declination',
    FIELD_MAJOR:         'Major axis',
    FIELD_MINOR:         'Minor axis',
    FIELD_RATIO:         'Axis ratio (a/b)',
    FIELD_BT:            'B-band (BT)',
    FIELD_VT:            'V-band (VT)',
    FIELD_MODULUS:       'Distance modulus',
    FIELD_MOD_ERR:       'Modulus error',
    FIELD_DISTANCE:      'Distance',
    GROUP_IDENTITY:      'Identity',
    GROUP_COORDS:        'Coordinates',
    GROUP_MORPHOLOGY:    'Morphology',
    GROUP_PHOTOMETRY:    'Photometry',
    GROUP_DISTANCE:      'Distance',
    GROUP_MORE:          'More',
    SCORE_TOTAL:         'Total visibility',
    SCORE_BEST:          'Best month',
    SCORE_PEAK:          'Peak score',
    MONTHLY_TITLE:       'Monthly visibility',
    CLOSE_ARIA:          'Close',
    popupAria:           (name: string) => `Galaxy ${name}`,
    pgcEyebrow:          (pgc: string)  => `PGC · ${pgc}`,
    objtypeSub:          (t: string)    => `Object type · ${t}`,
  },

  SKY2: {
    ZOOM_IN_ARIA:      'Zoom in',
    ZOOM_OUT_ARIA:     'Zoom out',
    RECENTER_ARIA:     'Recenter',

    CARDINAL_N:        'N',
    CARDINAL_NE:       'NE',
    CARDINAL_E:        'E',
    CARDINAL_SE:       'SE',
    CARDINAL_S:        'S',
    CARDINAL_SW:       'SW',
    CARDINAL_W:        'W',
    CARDINAL_NW:       'NW',

    // Visibility bar hover hints
    HINT_PROJ_RECT:    'Rectilinear Projection',
    HINT_PROJ_FISHEYE: 'Fisheye Projection',
    HINT_PROJ_STEREO:  'Stereographic Projection',

    HINT_STAR_FULL:        'Full HYG Catalogue · Stars',
    HINT_STAR_BALANCED:    'Balanced · Stars',
    HINT_STAR_PERF:        'Performance · Stars',

    HINT_GAL_FULL:         'Full PGC Catalogue · Galaxies',
    HINT_GAL_BALANCED:     'Balanced · Galaxies',
    HINT_GAL_PERF:         'Performance · Galaxies',

    HINT_GAL_MODE_VISUAL:  'Visual Size · Galaxies',
    HINT_GAL_MODE_TRUE:    'True 1:1 Size · Galaxies',

    HINT_SKY_TOGGLE:       'Atmospheric Sky',

    HINT_LAYER_SUN:            'Sun',
    HINT_LAYER_MOON:           'Moon',
    HINT_LAYER_STARS:          'Stars',
    HINT_LAYER_GALAXIES:       'Galaxies',
    HINT_LAYER_CONSTELLATIONS: 'Constellations',
    HINT_LAYER_GRID:           'Grid',
    HINT_LAYER_HORIZON:        'Horizon',
    HINT_LAYER_GROUND:         'Ground',
    HINT_LAYER_LABELS:         'Labels',

    SEARCH_ARIA:               'Search stars and galaxies',
    SEARCH_HINT:               'Search',
    SEARCH_PLACEHOLDER:        'Search stars and galaxies…',
    SEARCH_CLEAR_ARIA:         'Clear and close search',
    SEARCH_RESULTS_HEAD:       'Results',
    SEARCH_PROMPT_HEAD:        'Try a name…',
    SEARCH_EMPTY_NO_MATCHES:   'No matches for "{q}"',
    SEARCH_EMPTY_HIDDEN:       'No matches for "{q}". Stars or Galaxies are hidden — enable them in the top-right to widen the search.',
    SEARCH_RESULT_MAG:         'mag',
    SEARCH_RESULT_SEP:         ' · ',

    MOON_RISE:                 'Moonrise',
    MOON_SET:                  'Moonset',
    MOON_PHASE:                'Moon phase',
    MOON_PHASE_NEW:            'New Moon',
    MOON_PHASE_WAX_CRES:       'Waxing Crescent',
    MOON_PHASE_FIRST_QTR:      'First Quarter',
    MOON_PHASE_WAX_GIB:        'Waxing Gibbous',
    MOON_PHASE_FULL:           'Full Moon',
    MOON_PHASE_WAN_GIB:        'Waning Gibbous',
    MOON_PHASE_LAST_QTR:       'Last Quarter',
    MOON_PHASE_WAN_CRES:       'Waning Crescent',

    // Top-left selection card
    CARD_KIND_STAR:        'Star',
    CARD_KIND_GALAXY:      'Galaxy',
    CARD_GALAXY_CATALOGUE: 'PGC catalogue',
    CARD_FIELD_BAYER:      'BAYER',
    CARD_FIELD_HD:         'HD',
    CARD_FIELD_HR:         'HR',
    CARD_FIELD_GL:         'GL',
    CARD_FIELD_MAG:        'MAG',
    CARD_FIELD_ABS_MAG:    'ABS-MAG',
    CARD_FIELD_BV:         'B-V',
    CARD_FIELD_DIST:       'DIST',
    CARD_FIELD_RA:         'RA',
    CARD_FIELD_DEC:        'DEC',
    CARD_FIELD_ALT:        'ALT',
    CARD_FIELD_AZ:         'AZ',
    CARD_FIELD_SIZE:       'SIZE',
    CARD_FIELD_PA:         'PA',
    CARD_FIELD_ALT_NAMES:  'ALT NAMES',
    CARD_UNIT_LY:          'ly',
    CARD_UNIT_MLY:         'Mly',

    TIMELINE_PREV_DAY:  '−1 day',
    TIMELINE_TODAY:     'Today',
    TIMELINE_NEXT_DAY:  '+1 day',
    TIMELINE_PICK_DATE: 'Choose date…',

    DP_TITLE:           'Set observation time',
    DP_SUB:             'Choose any moment — RedShift will recompute the sky.',
    DP_CLOSE_ARIA:      'Close',
    DP_APPLY:           'Apply',
    DP_TIME_HOUR_ARIA:  'Hour',
    DP_TIME_MIN_ARIA:   'Minute',
    DP_TIME_STEP_UP:    'Increment',
    DP_TIME_STEP_DOWN:  'Decrement',
    DP_DATE:            'Date',
    DP_TIME_LABEL:      'Time',
    DP_TIME_HINT:       'local · 24h',
    DP_QUICK_SET:       'Quick set',
    DP_PRESET_TONIGHT:  'Tonight 22:00',
    DP_PRESET_MIDNIGHT: 'Astro midnight',
    DP_PRESET_RESET:    'Reset to now',
  },

  COMPLEXITY_SLIDER: {
    LABEL:    'Computation Precision',
    ARIA:     'Computation precision',
    LABELS:   ['Lowest', 'Low', 'Medium', 'High', 'Highest'] as const,
    valueText:(label: string, v: number) => `${label} · ${v}×${v}`,
  },

  GALAXY_COMPLEXITY_SLIDER: {
    LABEL:    'Computation Precision',
    ARIA:     'Galaxy computation precision',
    LABELS:   ['Standard', 'High', 'Maximum'] as const,
    valueText:(label: string, night: number, month: number) =>
                `${label} · ${night} pivots/night × ${month} days/month`,
  },

  DOCS: {
    TITLE:    'Documentation',
    SUBTITLE: 'Field guide for RedShift — short, practical, written by the people who built it.',
    KPI_ARTICLES:  'ARTICLES',
    KPI_BUILD:     'BUILD',
    KPI_VERSION:   'v1.0',
    SEARCH_PLACEHOLDER: 'Search the docs…',
    CLEAR_ARIA:    'Clear',
    CLEAR_BTN:     '×',
    suggestedEyebrow: (featureName: string) => `Suggested · you were just in ${featureName}`,
    READ_SUFFIX:   ' read',
    UPDATED_PREFIX:'Updated ',
    emptyTitle:    (query: string) => `No articles match "${query}"`,
    EMPTY_SUB:     'Try a broader term, or browse a category above.',
    ALL_ARTICLES:  'All articles',
    META_CATEGORY: 'CATEGORY',
    META_READ:     'READ',
    META_UPDATED:  'UPDATED',
    TOC_TITLE:     'On this page',
    TOC_EMPTY:     'No sections.',
    RELATED_TITLE: 'Related',
    CATEGORIES: ['All', 'Essentials', 'Modules', 'Workflow', 'Reference'] as const,
  },

  TOOL_PLACEHOLDER: {
    subtitle:  (label: string) =>
                 `Tool surface for ${label.toLowerCase()} — switch back to Select to see the full workspace.`,
    bodyBefore:(label: string) =>
                 `Select a layer in the workspace to apply ${label.toLowerCase()}. Press `,
    KBD_V:     'V',
    bodyAfter: ' to return to the move tool.',
  },

} as const;
